# Generated by Django 6.1.1 on 2026-09-10 04:25

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('internal_length_cm', models.DecimalField(decimal_places=2, max_digits=8, validators=[common.validators.validate_positive_nonzero])),
                ('internal_width_cm', models.DecimalField(decimal_places=2, max_digits=8, validators=[common.validators.validate_positive_nonzero])),
                ('internal_height_cm', models.DecimalField(decimal_places=2, max_digits=8, validators=[common.validators.validate_positive_nonzero])),
                ('max_weight_kg', models.DecimalField(decimal_places=3, max_digits=8, validators=[common.validators.validate_positive_nonzero])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, validators=[common.validators.validate_positive_nonzero])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['cost'],
            },
        ),
    ]
