# Generated by Django 6.1.1 on 2026-09-10 04:25

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('length_cm', models.DecimalField(decimal_places=2, max_digits=8, validators=[common.validators.validate_positive_nonzero])),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=8, validators=[common.validators.validate_positive_nonzero])),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=8, validators=[common.validators.validate_positive_nonzero])),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=8, validators=[common.validators.validate_positive_nonzero])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
